# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Vivado_Projects/MAS/Projekt/MAS_projekt.srcs/sources_1/bd/block_design_1/ip/block_design_1_auto_pc_2/block_design_1_auto_pc_2.xci
# IP: The module: 'block_design_1_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_Projects/MAS/Projekt/MAS_projekt.srcs/sources_1/bd/block_design_1/ip/block_design_1_auto_pc_2/block_design_1_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_1_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Vivado_Projects/MAS/Projekt/MAS_projekt.srcs/sources_1/bd/block_design_1/ip/block_design_1_auto_pc_2/block_design_1_auto_pc_2.xci
# IP: The module: 'block_design_1_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vivado_Projects/MAS/Projekt/MAS_projekt.srcs/sources_1/bd/block_design_1/ip/block_design_1_auto_pc_2/block_design_1_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_1_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
