# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq_pins.xdc

# Block Designs: bd/block_design_1/block_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1 || ORIG_REF_NAME==block_design_1} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_processing_system7_0_0/block_design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_processing_system7_0_0 || ORIG_REF_NAME==block_design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_ps7_0_axi_periph_0/block_design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==block_design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_rst_ps7_0_100M_0/block_design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==block_design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_xbar_0/block_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_xbar_0 || ORIG_REF_NAME==block_design_1_xbar_0} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_axi_gpio_0_1/block_design_1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_axi_gpio_0_1 || ORIG_REF_NAME==block_design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_axi_gpio_1_1/block_design_1_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_axi_gpio_1_1 || ORIG_REF_NAME==block_design_1_axi_gpio_1_1} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_blk_mem_gen_0_0/block_design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==block_design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_ov7670_bram_capture_0_0/block_design_1_ov7670_bram_capture_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_ov7670_bram_capture_0_0 || ORIG_REF_NAME==block_design_1_ov7670_bram_capture_0_0} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_axi_bram_ctrl_0_0/block_design_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==block_design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_auto_pc_1/block_design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_auto_pc_1 || ORIG_REF_NAME==block_design_1_auto_pc_1} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_auto_pc_0/block_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_auto_pc_0 || ORIG_REF_NAME==block_design_1_auto_pc_0} -quiet] -quiet

# IP: bd/block_design_1/ip/block_design_1_auto_pc_2/block_design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_1_auto_pc_2 || ORIG_REF_NAME==block_design_1_auto_pc_2} -quiet] -quiet

# XDC: bd/block_design_1/block_design_1_ooc.xdc
