# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_Projects/MAS/Projekt/MAS_projekt.srcs/sources_1/bd/block_design_1/ip/block_design_1_auto_pc_0/block_design_1_auto_pc_0.xci
# IP: The module: 'block_design_1_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projects/MAS/Projekt/MAS_projekt.srcs/sources_1/bd/block_design_1/ip/block_design_1_auto_pc_0/block_design_1_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_1_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vivado_Projects/MAS/Projekt/MAS_projekt.srcs/sources_1/bd/block_design_1/ip/block_design_1_auto_pc_0/block_design_1_auto_pc_0.xci
# IP: The module: 'block_design_1_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projects/MAS/Projekt/MAS_projekt.srcs/sources_1/bd/block_design_1/ip/block_design_1_auto_pc_0/block_design_1_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_1_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
